version: '3.4'
services:
  nginx:
    image: nginx
    container_name: onlinemall-web
    ports:
    - "8090:8090"
    volumes: 
      - ./dist:/var/log/nginx
    restart: always
networks:
  default:
    external:
      name: docker_default