version: '3.4'
services:
  nginx:
    image: nginx
    container_name: onlinemall-web
    ports:
    - "8090:8090"
    restart: always
    command: 
      - /bin/bash
      - -c
      - |
        mkdir -p /app
        cp -R ./dist /app
networks:
  default:
    external:
      name: docker_default